export const FETCH_POKEMON_LIST_REQUEST = "FETCH_POKEMON_LIST_REQUEST";
export const FETCH_POKEMON_LIST_SUCCESS = "FETCH_POKEMON_LIST_SUCCESS";
export const FETCH_POKEMON_LIST_FAILURE = "FETCH_POKEMON_LIST_FAILURE";
export const HAS_MORE = "HAS_MORE";

export const FETCH_POKEMON_DETAILS_REQUEST = "FETCH_POKEMON_DETAILS_REQUEST";
export const FETCH_POKEMON_DETAILS_SUCCESS = "FETCH_POKEMON_DETAILS_SUCCESS";
export const FETCH_POKEMON_DETAILS_FAILURE = "FETCH_POKEMON_DETAILS_FAILURE";
