export const FETCH_POKEMON_LIST_REQUEST = "FETCH_POKEMON_LIST_REQUEST";
export const FETCH_POKEMON_LIST_SUCCESS = "FETCH_POKEMON_LIST_SUCCESS";
export const FETCH_POKEMON_LIST_FAILURE = "FETCH_POKEMON_LIST_FAILURE";
export const HAS_MORE = "HAS_MORE";

export const FETCH_POKEMON_DETAILS_REQUEST = "FETCH_POKEMON_DETAILS_REQUEST";
export const FETCH_POKEMON_DETAILS_SUCCESS = "FETCH_POKEMON_DETAILS_SUCCESS";
export const FETCH_POKEMON_DETAILS_FAILURE = "FETCH_POKEMON_DETAILS_FAILURE";

export const FETCH_SPECIES_REQUEST = "FETCH_SPECIES_REQUEST";
export const FETCH_SPECIES_SUCCESS = "FETCH_SPECIES_SUCCESS";
export const FETCH_SPECIES_FAILLURE = "FETCH_SPECIES_FAILLURE";

export const FETCH_EVOLUTION_CHAIN_REQUEST = "FETCH_EVOLUTION_CHAIN_REQUEST";
export const FETCH_EVOLUTION_CHAIN_SUCCESS = "FETCH_EVOLUTION_CHAIN_SUCCESS";
export const FETCH_EVOLUTION_CHAIN_FAILLURE = "FETCH_EVOLUTION_CHAIN_FAILLURE";

export const FETCH_POKEMONS_FROM_EVOLUTION_REQUEST =
  "FETCH_POKEMONS_FROM_EVOLUTION_REQUEST";
export const FETCH_POKEMONS_FROM_EVOLUTION_SUCCESS =
  "FETCH_POKEMONS_FROM_EVOLUTION_SUCCESS";
export const FETCH_POKEMONS_FROM_EVOLUTION_FAILLURE =
  "FETCH_POKEMONS_FROM_EVOLUTION_FAILLURE";

export const ADD_TO_FAVORITE_LIST = "ADD_TO_FAVORITE_LIST";
export const REMOVE_FROM_FAVORITE_LIST = "REMOVE_FROM_FAVORITE_LIST";

export const FETCH_TEAM_REQUEST = "FETCH_TEAM_REQUEST";
export const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_FAILLURE = "FETCH_TEAM_FAILLURE";
